openapi: 3.0.0
info:
  title: MistDB API
  version: '0.0.1'

servers:
  - url: /api
    description: relative path to the API end points

paths:
  /login:
    post:
      tags: [Auth]
      summary: Return JWT token
      #operationId: app.api.access.login
      operationId: app.demo.routes.demo_index
      description: Login procedure
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              x-body-name: user
              properties:
                username:
                  type: string
                  description: Username
                password:
                  type: string
                  description: Password
                client_version:
                  type: string
                  description: Client API version
      responses:
        '200':
          description: JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  token:
                    type: string
                    description: JWT token
